name: itvlist

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.4

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run itv_all
        run: python ${{ github.workspace }}/itv_all.py
     
      #- name: Run hnitv
        #run: python ${{ github.workspace }}/hnitv.py
        
      #- name: Run itv
        #run: python ${{ github.workspace }}/itv.py

      #- name: Run itvtest
        #run: python ${{ github.workspace }}/itvtest.py
      
      #- name: Run cctv
        #run: python ${{ github.workspace }}/cctv.py
        
      #- name: Run weishi
        #run: python ${{ github.workspace }}/weishi.py
        
      #- name: Run hn
        #run: python ${{ github.workspace }}/hn.py
        
      #- name: Run qita
        #run: python ${{ github.workspace }}/qita.py
        

      #- name: Upload a Build Artifact
        #uses: actions/upload-artifact@v4.0.0
        #with:
          #name: itv
          #path: ${{ github.workspace }}/

      - name: 提交更改
        run: |
          git config --local user.email "mrxuanyu@gmail.com"
          git config --local user.name "chaxy123"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
